[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node src/app.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/api/health"
port = 5000
timeout = 10

[env]
NODE_ENV = "production"
